### PR TITLE
Frontend error handling

### PR DESCRIPTION
**Pull request by Rex2002**

### CODE REVIEW

**Review by MalteRichert — COMMENTED** [review]
Looks good as far as my js knowledge goes. Can we test the error sackbar somehow?

**Comment by Rex2002** [comment]
not properly, did not manage to create errors, because unknown status's are just ignored, but managed to test the displaying manually by pretending to receive an error each time lobby-status was received in the frontend

**Comment by yannickkirschen** [comment]
I am confused - why are there changes in the Workflow or static files? Have you branched from the latest main?

**Review by yannickkirschen — APPROVED** [review]

**Comment by yannickkirschen** [comment]
Very strange, but I just approved the changes. Please squash it so we remain a tidy commit history ;)

**Pull request merged**
